### PR TITLE
Performance upgrades

### PR DESCRIPTION
**Pull request by marcusklaas**
This crate is great, and when I looked under the hood I found some opportunities for performance improvements. Most of the changes in this PR are to remove as many allocations as possible. In particular, the duels should now not allocate at all after the first one. On my machine, the time per 100 duels went from ~44 microseconds to about 15 microseconds. I also took the opportunity to add a proper error enum.

I know that these are pretty large changes and that this repo is in maintenance mode, so do with this PR what you will :-)

### CODE REVIEW

**Comment by DataWraith** [comment]
Wow, Thank you! 

It might take me a few days until I can review and merge all of it; I'll write a more thorough response then.

**Comment by DataWraith** [comment]
Hi.

First, thank you for the pull request again. I finally had time to sit down and review it.

I like some of the changes you've made, but I'm not sure the performance improvement is worth it.
My main gripe is that I like to keep things immutable as much as possible, and the performance changes all make things mutable.

* You implemented a `TeamParams` struct, which is more elegant than   having four separate vectors. Same with the `.enumerate()` for-loops. 
  I'd like to use that part of the code.

* The vector of TeamParams is cached in `Rater`, which necessitates making   `Rater` mutable. The cached TeamParams vector is reinitialized every time   `update_rating` is called. While that does help over just making a new vector
  every time, on my laptop this only saves about 1.5µs for 100 duels, and I   can't imagine someone being bottlenecked there when you can run 100.000+ duels   per second on modest hardware -- I'd like to keep `Rater` immutable, and view
  this as an acceptable tradeoff.

* Updating the ratings in-place saves 0.1µs per duel on my machine, again, at   the cost of making things mutable. It is debatable whether mutable ratings may   even be a more intuitive way to handle duels, but I decided against it while
  implementing the crate originally, and I don't think that it is worth it to   potentially disrupt downstream code using the crate with an API change.

* Adding a proper error struct is a nice change, but again, I'm not sure it is worth the downstream API breakage, given that the two possible errors are programmer errors and not something that might occur in regular use and needs to be matched against.

Overall, I'd like to cherry-pick some of the changes, but I won't be merging the whole thing as is.

**Comment by marcusklaas** [comment]
I understand that the breaking API changes are too severe for the bump in throughput. Thank you for explaining your considerations so clearly.

There are still some things that can be done to make at least the duels faster without introducing backward incompatible changes. We could abstract the update logic to a non allocating (private?) method and have `update_rankings` basically wrap that by allocating temporary buffers for the team parameters and the output vectors. The `duel` method could call this internal method without allocating.

**Comment by DataWraith** [comment]
I'm sorry for not having addressed this sooner, but I don't think I will be
making many more changes to this crate -- it does what it should, and it is
fast enough to not be a bottleneck in a surrounding system.

I appreciate your effort and ideas, and I acknowledge that the crate could
probably be made faster, but I don't want it to be at the expense of
ergonomics/simplicity.

I'm closing this pull request now.

**Pull request closed without merging**
